# frozen_string_literal: true

require 'rubocop'
require 'rubocop/cop/betterment/utils/parser'
require 'rubocop/cop/betterment/utils/method_return_table'
require 'rubocop/cop/betterment/utils/hardcoded_attribute'
require 'rubocop/cop/betterment/authorization_in_controller'
require 'rubocop/cop/betterment/dynamic_params'
require 'rubocop/cop/betterment/unscoped_find'
require 'rubocop/cop/betterment/unsafe_job'
require 'rubocop/cop/betterment/timeout'
require 'rubocop/cop/betterment/memoization_with_arguments'
require 'rubocop/cop/betterment/non_standard_actions'
require 'rubocop/cop/betterment/site_prism_loaded'
require 'rubocop/cop/betterment/spec_helper_required_outside_spec_dir'
require 'rubocop/cop/betterment/implicit_redirect_type'
require 'rubocop/cop/betterment/active_job_performable'
require 'rubocop/cop/betterment/allowlist_blocklist'
require 'rubocop/cop/betterment/server_error_assertion'
require 'rubocop/cop/betterment/hardcoded_id'
require 'rubocop/cop/betterment/vague_serialize'
require 'rubocop/cop/betterment/fetch_boolean'
require 'rubocop/cop/betterment/status_code'
