name: TriageDependabotPRs
on:
  pull_request_target:
    types: 
      - opened
      - reopened

permissions:
  pull-requests: write

jobs:
  TagReviewers:
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: [ubuntu-latest]
    steps:
      - name: Tag reviewers in dependabot PRs
        run: gh pr comment "$PR_URL" --body "/domain @Betterment/rubocop-betterment-core<br/>/platform @Betterment/rubocop-betterment-core<br/><br/><sub>[Documentation&#58; Dependabot Alerts]($DOC_LINK)</sub>"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DOC_LINK: ${{ secrets.DOC_LINK }}
