name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "3.3", "3.4"]
        gemfile:
          - Gemfile

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: ruby/setup-ruby@09a7688d3b55cf0e976497ff046b70949eeaccfd # v1.288.0
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run linter
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: bundle exec rubocop --parallel
      - name: Run tests
        env:
          BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        run: bundle exec rake
